application: vitalmenu
version: 10
runtime: python
api_version: 1

admin_console:
  pages:
  - name: Stats
    url: /_ah/stats/

builtins:
- datastore_admin: on
- appstats: on
- remote_api: on

handlers:
- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: favicon\.ico
  mime_type: image/x-icon

- url: /.*
  script: main.py


